const STORAGE_KEYS = {
  USER: 'pet_user',
  PETS: 'pet_pets',
  ORDERS: 'pet_orders',
  USER_ORDERS: 'pet_user_orders',
  MERCHANT_ORDERS: 'pet_merchant_orders',
  CONTRACTS: 'pet_contracts',
  BILLS: 'pet_bills',
  LEDGER: 'pet_ledger',
  DEMO_LEDGER: 'pet_demo_ledger',
  DAILY_LOGS: 'pet_daily_logs',
  CHATS: 'pet_chats',
  SHOP: 'pet_shop',
  STORE_ID: 'pet_store_id',
  CURRENT_STORE: 'pet_current_store',
  USER_CLIENT_MODE: 'pet_user_client_mode',
  MERCHANT_SHELL_MODE: 'pet_merchant_shell_mode',
  SAVED_USER_VISIT_STORE_ID: 'pet_saved_user_visit_store_id',
  BILLING_RULES: 'pet_billing_rules',
  CONTRACT_TEMPLATE: 'pet_contract_template',
  IMAGE_CACHE: 'pet_image_cache',
  DEMO_INITIALIZED: 'pet_demo_initialized',
  DEMO_ORDERS: 'pet_demo_orders',
  DEMO_PETS: 'pet_demo_pets',
  DEMO_DAILY_LOGS: 'pet_demo_daily_logs',
  DEMO_SHOP: 'pet_demo_shop',
  DEMO_APPLY_DRAFT: 'pet_demo_apply_draft',
  DEMO_CONTRACTS: 'pet_demo_contracts',
  RESERVE_CONTACT: 'pet_reserve_contact',
  PET_BUTLER: 'pet_butler',
  AI_CONSULT: 'pet_ai_consult',
  ANNOUNCEMENT_READ: 'pet_announcement_read',
  ANNOUNCEMENT_CACHE: 'pet_announcement_cache',
  ANNOUNCEMENT_CACHE_AT: 'pet_announcement_cache_at'
};

module.exports = { STORAGE_KEYS };
